### ISSUE TITLE
Can I know the log (numbers) of items in a particular class?

### ISSUE THREAD

**Issue by blackShine-2** [SkalskiP/make-sense#247] opened 2022-05-02 07:28 UTC
It would be very easy if I can know the number of items in each class after labelling is done.

**Comment by SkalskiP** [comment] 2022-07-22 16:13
Looks like the issue is a duplicate of: https://github.com/SkalskiP/make-sense/issues/76.

**Closed by SkalskiP** 2022-07-22 16:13 UTC
Labels: duplicate
