### ISSUE TITLE
[feature request] load existing annotations

### ISSUE THREAD

**Issue by bilylee** [SkalskiP/make-sense#32] opened 2019-08-27 13:01 UTC
**Is your feature request related to a problem? Please describe.**
re-edit existing annotations

**Describe the solution you'd like**
add an import button to load existing annotations

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by SkalskiP** [comment] 2019-08-27 20:25
@bilylee As an explanation. Would you like to be able to import photos with labels so that you can make some changes and re-export them?

**Comment by bilylee** [comment] 2019-08-28 02:25
For example, given a list of images, objects are first detected via a pretrained detector. Then, these detections are loaded in the make-sense tool and manually refined.

For now, there is an export button for exporting annotations. I would like an import button that load existing annotations. It is not necessary to load both images and annotations at the same time, we can first load images and then load corresponding annotations.

**Comment by SkalskiP** [comment] 2019-08-28 06:42
@bilylee Then the title of issue does not fully reflect what you have described now. Because from what I understand, a few things have been mixed up here. And to be quite honest, we are working on each one of them.

* **Loading existing annotations** - which in my opinion means that you already have a labelled images, for example in VGG format. In this situation, the user uploads files to the browser and makesense.ai decodes and visualizes BBoxes. Then you can either edit them or export them in a different format.

* **Support for labelling** - In this situation, makesense.ai allows you to use existing and trained models to detect what's in the photos. **In this situation, the annotation does not exist, you just supply a photo and the model would have to make a prediction.** We are already having advanced discussions on this subject, but we are still considering the form of this functionality. Can we do it in JS or on Backend? Should we provide such a trained model or make it possible to send queries to some external API? If the model is trained earlier, what classes of objects should we support?

**Comment by yyuuliang** [comment] 2019-08-28 23:55
I also think the ability to edit existing annotations is important. That is the first one on your list, "loading existing annotations", thanks

**Comment by SkalskiP** [comment] 2019-08-29 07:12
I agree - it gives you the opportunity to:
- return to the project you were working on
- verify that your labels are correct
- possibly transform to another format. 

In this situation I will try to add the possibility of importing ready-made labels.

**Comment by zhreshold** [comment] 2019-08-30 01:31
Is it possible to keep a state of the project when starting it locally using `npm`?
Currently when the page is refreshed, everything get lost(project configs, images, labels).
Also it would be awesome to start with some preset local projects with images already loaded for labeling.

**Comment by SkalskiP** [comment] 2019-08-30 07:42
Hi @zhreshold . First of all, I would just like to point out that your comment could easily become a separate issue. At the moment, makesense.ai does not have the ability to save the state of the application during the labeling process. This topic often appears in conversations - because a lot of people would like to have some possibility to saving. However, the problem is complicated.

Launching the application on our site, and running it locally from a console using the `npm`, does not really change anything. It is still a browser application that does not have access to the filesystem and therefore cannot save and read files from your disk. It is possible to write a functionality that would record the status of labels while the application is running, using browser local storage. The question is whether this will help anyone if they will not be able to save the photos as well. And the browser won't let you do that. 

There are plans to give the user the opportunity to connect to his S3 on the Amazon in the further development phase of the application. This would be one way to save the application status. You can also think about creating an application in Electron by using a code written in React. All these ideas are, however, a relatively distant future. I would be happy to hear your opinion and ideas.

**Comment by bourdakos1** [comment] 2019-08-30 12:40
@SkalskiP This probably isn’t the right place, but I’ve been following your project for a bit and I really like it. I’ve been working on a similar project: https://github.com/cloud-annotations

With my tool, all your projects are connected to an s3 bucket to sync images and annotations. However, I really like your stateless approach, as it gives users the opportunity to not be bound to a cloud provider. Also, my tool is lacking polygon and point support. Would you be interested in teaming up/working together in any way?

**Comment by zhreshold** [comment] 2019-08-30 17:30
@SkalskiP Thanks for the explaination. I now understand the technical limitation.
From the perspective of a user, this online tool is awesome in UI/UX and labeling exprience. However,  I wish the tool to be trustworthy to be able , i.e., resume my previous work whenever I want without worry about the accidental  loss of annatations for example crashing browser. 

And the stateless project means I have to manually manage all my images (labeled, un-labeled...) which is not feasible for a large dataset.

So far I found it's perfect for occasionally labeling less than 20 images at a time. If some s3 backup feature is integrated I guess it's capable of handling much bigger job.

Thanks again for the awesome project, I will stay tuned.

**Comment by SkalskiP** [comment] 2019-08-30 20:19
@zhreshold What a great idea for makesense.ai was born on a hackathon, when due to the lack of a good editor for labeling photos we lost a lot of time fighting with tools that had their limitations. Therefore, Make Sense was to become something that would allow you to quickly and dirty perform a huge amount of manual work without unnecessary configuration. I'm aware of his limitations. So far I've heard from a few companies asking me if I plan to develop functionalities allowing to connect to Amazon S3 or other cloud. It's a very interesting idea and I know it can make makesense.ai really big. I have a lot of work ahead of me!

**Comment by pixelatedbrian** [comment] 2019-09-04 16:13
Hi, thanks SkalskiP for making such a great tool.  I have noticed a couple of bugs, some of which crash the webpage during annotation and any work done is lost.  I have taken to periodically saving because of this issue but this won't help until we are able to load previous files and continue modifying.

Can you please prioritize this particular item because it will help alleviate the symptoms of other issues.

Thanks again for making a great tool.

**Comment by SkalskiP** [comment] 2019-09-04 18:01
Hi, @pixelatedbrian! First of all, thank you very much for your kind words. They are a great motivation. Secondly, there is no denying that this functionality is currently one of the most requested. You can see it both because of how active is the discussion under this issue and by the number of upvots. In this situation we will certainly have to speed up the implementation of this mechanism. At the moment the order of functionality implementation is as follows:

1. Improving the keyboard shortcut mechanism - at the moment we have only the basics.
2. Zoom in/out
3. ??? - Maybe we should place loading of existing labels here

Thirdly, if you noticed that the application is crashing and you can describe in what situations it happens, please report the issue. I would be very grateful.

**Comment by smitheric95** [comment] 2020-04-28 15:21
Hi,

Are there any plans on implementing this feature soon?

Fantastic tool btw!

**Comment by SkalskiP** [comment] 2020-09-02 18:07
Hello @bilylee, @yyuuliang, @zhreshold, @bourdakos1, @pixelatedbrian First PR, with the loading of COCO segmentation labels is open for review: https://github.com/SkalskiP/make-sense/pull/111. Would be great if you could find some time to take a look.

**Comment by SkalskiP** [comment] 2020-09-04 06:07
I am happy to inform you that it is now possible to load labels from COCO format files. This way you can load the annotations in the form of a bbox and segmentation. The Feature is still very fresh so for some time it will only be available on the dev instance. https://develop.makesense.ai/ I am not closing this issue because it is only the first of a whole series of PRs, in which I will add a few more formats that you will be able to load. I have already started working on loading labels in YOLO format.

**Comment by SkalskiP** [comment] 2020-09-12 21:29
Hi all. Just added loading of existing YOLO annotations into MakeSense. You can test it on our test instance:  https://develop.makesense.ai/

**Comment by hemanth-thallapaneni** [comment] 2021-02-10 05:03
Hi @SkalskiP, How does this Importing annotations work...? I tried exporting the annotation which I made in makesence.ai only which gave me the coordinates of the shape...but when I tried importing annotation it is asking for labels.txt file which is not present in the exported annotation so I made a txt file with labels even then  it is asking to load correctly...

**Comment by kalfasyan** [comment] 2021-04-21 09:14
Same problem as @hemanth-thallapaneni. I get an unexpected occurred while parsing my yolo txt file.  
Example few lines of my yolo txt file:  
`t,0.6894723865877712,0.053782894736842106,0.008629191321499015,0.011513157894736841
v,0.8583579881656804,0.06036184210526316,0.011587771203155819,0.015460526315789473
v,0.5878944773175543,0.06546052631578947,0.01282051282051282,0.017105263157894738
m,0.7287968441814595,0.0694078947368421,0.008382642998027613,0.01118421052631579
t,0.9050788954635108,0.07960526315789473,0.014792899408284023,0.019736842105263157
m,0.8933678500986193,0.09588815789473684,0.017011834319526627,0.022697368421052633
m,0.9360207100591716,0.08207236842105263,0.01799802761341223,0.02401315789473684
v,0.48101577909270216,0.06694078947368422,0.012080867850098619,0.01611842105263158
v,0.488905325443787,0.06595394736842106,0.010848126232741617,0.014473684210526316`

**Comment by kalfasyan** [comment] 2021-04-21 09:47
@hemanth-thallapaneni after converting my string labels to integers and using spaces instead of commas, makesense.ai managed to import my annotations

**Comment by manaclan** [comment] 2021-06-22 08:59
Hi @SkalskiP, I got the same problem as @hemanth-thallapaneni. I tried to import my new exported YOLO annotations but the annotations didn't appear. Here is one of my labels.txt
0 0.533922 0.234206 0.191063 0.184900

**Comment by jay-bhambhani** [comment] 2021-06-29 20:37
@SkalskiP - I actually think I can help you with this! My company loves makesense, and we want to scale it out. I might be able to help by creating a something similar to https://github.com/jupyterhub/kubespawner for kubernetes. would you be interested in taking a peek once I get going?

**Comment by wyattroberts** [comment] 2021-07-19 20:56
The ability to edit existing annotations would seem like a trivial change to implement. Your program is absolutely fantastic! However, the inability to edit existing annotations is a showstopper. I just wasted hours of my time :(

**Comment by jithinvijay** [comment] 2022-03-23 12:30
It worked for me. To import yolo annotations, you should have a "labels.txt" file along with all the other annotation txt files. The labels.txt file should contain your class names each in a new line. That's it.

**Comment by SkalskiP** [comment] 2022-03-29 07:04
@hemanth-thallapaneni, @kalfasyan, @manaclan, @wyattroberts first of all I'm really sorry for the late response. I had some personal problem that basically stopped me from working on make sense. Take a look at this issue. I described here how to reupload your labels into the editor. https://github.com/SkalskiP/make-sense/issues/222

@wyattroberts the ability to reupload labels into the editor was there from the beginning. What I think we need is much much much better documentation, so that people would know how to do it.

**Comment by SkalskiP** [comment] 2022-03-29 07:06
@jay-bhambhani any updates? Did you manage to scale it out?

**Closed** 2022-07-28 19:13 UTC
Labels: new-feature
