### ISSUE TITLE
Load Files with Label Description - How does the label file have to be formatted? Please provide an Example File.

### ISSUE THREAD

**Issue by PUKL-XXXL** [SkalskiP/make-sense#100] opened 2020-07-08 06:58 UTC
**Is your feature request related to a problem? Please describe.**

I would like to load previously defined Labels (which would be technically possible). Unfortunately I don't know how this input has to look like/be formatted.

**Describe the solution you'd like**

Please provide an example file.

**Describe alternatives you've considered**

-

**Additional context**

**Comment by SkalskiP** [comment] 2020-07-28 18:03
Hi @PUKL-XXXL! That functionality is not yet added to MakeSense.

**Comment by SkalskiP** [comment] 2020-07-28 18:06
This issue is duplicate of #32.

**Closed by SkalskiP** 2020-07-28 18:06 UTC
Labels: idea, question
