### ISSUE TITLE
No file name in the csv file if more than 1 images in the project

### ISSUE THREAD

**Issue by yyuuliang** [SkalskiP/make-sense#37] opened 2019-08-29 00:13 UTC
**Describe the bug**
I loaded two images in the project, make annotations on both images, then export the csv file. There is no file name in the csv data, so it is impossible to tell which points locations belongs to which image

**To Reproduce**
1. Load two images
2. Make points annotations
3. Export as csv file

**Expected behavior**
There should be a filename column in the csv file. Like this:
file1.jpg,lane1,217,556,01080.jpg,1640,590
file1.jpg,lane1,314,503,01080.jpg,1640,590
file1.jpg,lane1,410,458,01080.jpg,1640,590
file1.jpg,lane1,492,415,01080.jpg,1640,590
file1.jpg,lane1,564,383,01080.jpg,1640,590
file1.jpg,lane1,633,349,01080.jpg,1640,590
file1.jpg,lane2,1581,454,01080.jpg,1640,590
file1.jpg,lane2,1486,430,01080.jpg,1640,590
file1.jpg,lane2,1402,411,01080.jpg,1640,590
file1.jpg,lane2,1263,378,01080.jpg,1640,590
file1.jpg,lane2,1171,353,01080.jpg,1640,590
file2.jpg,lane1,217,556,01080.jpg,1640,590
file2.jpg,lane1,314,503,01080.jpg,1640,590
file2.jpg,lane1,410,458,01080.jpg,1640,590
file2.jpg,lane1,492,415,01080.jpg,1640,590
file2.jpg,lane1,564,383,01080.jpg,1640,590
file2.jpg,lane1,633,349,01080.jpg,1640,590
file2.jpg,lane2,1581,454,01080.jpg,1640,590
file2.jpg,lane2,1486,430,01080.jpg,1640,590
file2.jpg,lane2,1402,411,01080.jpg,1640,590
file2.jpg,lane2,1263,378,01080.jpg,1640,590
file2.jpg,lane2,1171,353,01080.jpg,1640,590

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubnuntu 16
 - Browser: Chrome
 - Version: 70

**Comment by SkalskiP** [comment] 2019-08-29 07:09
Hi @yyuuliang ! Thanks for reporting. It seems that this is a problem associated with #36 that you have reported. Point export only from files where you have a rect defined. Both problems will be fixed in the near future. As for the file name, it is given in every line of the CSV file. Simply because of what I wrote above, you managed to export only labels for one photo.

lane1,217,556,`01080.jpg`,1640,590

**Comment by SkalskiP** [comment] 2019-08-29 15:24
The problem has been solved. The improved version of the application will be available on the production with the next release. Currently, the patches are available on the developer instance: https://develop.makesense.ai/ I would be very grateful if you could verify whether the effect is as intended.

**Comment by yyuuliang** [comment] 2019-08-29 22:50
I have also tried this one, now I can get a complete csv list! thanks for the work!

**Comment by SkalskiP** [comment] 2019-08-30 07:55
You're welcome. Thank you very much for drawing attention to this problem. Keeping your application in a condition that allows you to use it is priority number 1. Task is for now `In Test` and I will move it to done, after another release.

**Comment by SkalskiP** [comment] 2019-09-04 18:07
Due to the large amount of bugs that we have managed to fix recently, we decided to make a small release marked with the tag `1.2.1-alpha`. The same applies to this issue, which is now available at https://makesense.ai 

Happy Labelling!

**Closed by SkalskiP** 2019-09-04 18:07 UTC
Labels: bug
