### ISSUE TITLE
Save progress or uplode csv labels

### ISSUE THREAD

**Issue by nieszkodzi** [SkalskiP/make-sense#53] opened 2019-09-13 11:08 UTC
In my team we are searching for some good labeling stuff and we finally found make-sense. It is very nice looking, easy to use tool, but I have some problems with it.

1. Is there any solution for saving project progress or (better) loading file with image names and labels just to keep labeling after restart of computer?

2. Is there (or will be) any solution for sharing work with many people labeling at the same time?

3. It will be nice to have information how many photos was labeled and how many are still to do.

Thank you for any answer.

**Comment by SkalskiP** [comment] 2019-09-13 17:42
@nieszkodzi! First of all, thank you very much for your kind words. I try very hard to make makesense.ai as simple and comfortable to use as possible. As far as your questions are concerned, we have a lot of things on the agenda and I am not hiding that the ideas you mentioned have already been discussed in other issues. And these are very good ideas! But there is but... 

Originally makesense.ai was meant to be a fast and dirty tool that would be ideal for hackatons or for research workers who do not want to pay others for access to tools that represent better quality. The development of makesense.ai lies very close to my heart, but unfortunately at the moment I am the only person who creates it. As a result, it will be very difficult for me to implement such extensive functionalities. Summing up, I am very open to cooperation, all pull requests and discussions about featuras. If you would like to contribute, I think everything is possible :)

**Comment by SkalskiP** [comment] 2020-07-28 18:06
This issue is duplicate of #32.

**Closed by SkalskiP** 2020-07-28 18:06 UTC
Labels: duplicate, question
