### ISSUE TITLE
Feature which displays total Items in each class

### ISSUE THREAD

**Issue by PIjarihd** [SkalskiP/make-sense#224] opened 2022-01-17 07:22 UTC
I would like to request you to add the feature where I can see the total numbers of objects in each class. I am labelling images for multiple classes. And I am not sure how many images do I have in each class. And, it is really a troublesome job to count because the class numbers is 84. So, is it possible to display automatically? Please add this if possible.

**Comment by SkalskiP** [comment] 2022-02-28 19:44
Hi @PIjarihd, sorry for the late response. I had some problems that slowed me down. Is that a duplicate of that issue https://github.com/SkalskiP/make-sense/issues/76? Am I correct?

**Comment by PIjarihd** [comment] 2022-03-03 05:36
Yes. You are right.

**Comment by SkalskiP** [comment] 2022-03-03 16:21
@PIjarihd In this situation, let me close your issue to clear the list of open tickets. I want you to know, however, that I really want to add this feature to Make Sense.

**Closed by SkalskiP** 2022-03-03 16:21 UTC
